hello: helloLinkedList.c linkedList
	gcc helloLinkedList.c linkedList.o -I. -o helloLinkedList

stack: stack.c linkedList
	gcc stack.c linkedList.o -I. -o stack
	
linkedList: linkedList.h linkedList.c
	gcc -c linkedList.c -I. -o linkedList.o
