build123: build123.c btree
	gcc build123.c btree.o -I. -o build123

randomTree: randomTree.c btree
	gcc randomTree.c btree.o -I. -o randomTree

btree: binaryTree.h binaryTree.c
	gcc -c binaryTree.c -I. -o btree.o
